# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Top
description: Digital Book of World Records for High Performance Computing
baseurl: "/top" # the subpath of your site, e.g. /blog
permalink: /:year/:title/
url: ""

# Logo settings
logo-image-url: assets/images/code-logo.svg
#font-awesome-icon-logo: fa-code

# Social settings
github_username: hpsee
twitter_username: askcyberinfra
repo: https://www.github.com/hpsee/top

# Build settings
markdown: kramdown
